spring.application.name=pockit

spring.datasource.url=jdbc:mysql://mysql-398a3621-was-e61a.j.aivencloud.com:28954/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_JaymYDpPEOiOGrPUNhk
